[chk_deployed_ids] [chk_metadata] [chk_nonexistent_ids] Made interface prettier

diff --git a/src/chk_metadata b/src/chk_metadata
--- a/src/chk_metadata
+++ b/src/chk_metadata
@@ -25,4 +25,5 @@ chk_metadata() {
         [[ $? -eq 0 ]] && { _ansi up 2; echo -en '\033[K'; } || { echo "[>>>>>>] Error reported"; cat ${STDERR}; local ERR=true; }
         local COUNT=$(( ${COUNT} + 1 ))
     done
+    [[ "${ERR}" == "true" ]] && { _msg EXEC "Metadata check completed with errors"; _msg WARN; } || { _msg EXEC "Metadata check completed succesfully"; _msg OK; }
 }
diff --git a/src/chk_nonexistent_ids b/src/chk_nonexistent_ids
--- a/src/chk_nonexistent_ids
+++ b/src/chk_nonexistent_ids
@@ -14,17 +14,25 @@ chk_nonexistent_ids() {
     local TARGET="${1}"
     local DB_FILE="${2}"
 
-    for row in $(awk 'BEGIN{RS="\n";FS="\t";OFS="="}{print $2,$3,$4}' ${DB_FILE}); do
+    local ERR=false
+    local rowList=($(awk 'BEGIN{RS="\n";FS="\t";OFS="="}{print $2,$3,$4}' "${DB_FILE}"))
+
+    local COUNT=1
+    for row in ${rowList[@]}; do
         local IMAGEID="$(cut -d"=" -f1 <<< ${row})"
         local TRACKID="$(cut -d"=" -f2 <<< ${row})"
         local FILE="$(cut -d"=" -f3 <<< ${row})"
-        _msg ECHO "Checking track id ${TRACKID}"
-        
+         
+        echo "[ ${COUNT} / ${#rowList[@]} ] Checking path of ${TRACKID}"
+
         if [[ ! -f "${TARGET}/${FILE}" ]] && [[ ${FILE} != "null" ]]; then
-            _msg ECHO "${TRACKID} points to non-existent file"
-            sed -i "/${IMAGEID}	${TRACKID}/d" ${DB_FILE}
+            gawk -i inplace -v imageid=${IMAGEID} trackid=${TRACKID} 'BEGIN{FS="\t";OFS="\t"}{if($2==imageid && $3==trackid){$4="null"}{print $0}}' ${DB_FILE}
+            local $?=1
         fi
+        [[ $? -eq 0 ]] && { _ansi up 2; echo -en '\033[K'; } || { echo "[>>>>>>] Error reported"; echo "${TRACKID} of ${IMAGEID} points to non-existent file"}; local ERR=true; }
+        local COUNT=$(( ${COUNT} + 1 ))
     done
+    [[ "${ERR}" == "true" ]] && { _msg EXEC "Nonexistent files check completed with errors"; _msg WARN; } || { _msg EXEC "Nonexistent files check completed succesfully"; _msg OK; }
 
 }
 
