[cmd_import] Updated documentation [cmd_import_tracks] Rewrote function to accomodate fragmented files [cmd_import_images] Renamed cmd_import_cueripper to cmd_import_images in preparation for rewri te of import_images functions [gen_cue] Adjusted variable names to fit actual output of print_meta functions [gen_image] Removed error messages in favor of exit codes [gen_mtag] Rewrote to accomodate multiple track files. [import_dir] Added to deal with importing directories after consolidation by import_track [import_cueripper] Renamed to import_images in preparation for rewrite [import_track] Added to deal with consolidation of disparate track files [import_tracks] Removed in favor of import_track and import_dir functions [iszip] Added as an easy way to see if zip file [print_meta_track] Renamed function

diff --git a/src/cmd_import_tracks b/src/cmd_import_tracks
--- a/src/cmd_import_tracks
+++ b/src/cmd_import_tracks
@@ -6,17 +6,43 @@
 #   cmd_import_tracks - Wrapper for import_tracks
 #
 # USAGE
-#   cmd_import_tracks </path/to/work/dir> <subpath/to/album>
+#   cmd_import_tracks </path/to/git/dir> </path/to/dir_or_archive>
 #
 # }
 
 cmd_import_tracks() {
-    local ROOT="${1}"; shift 1
-    local dirList=("${@}")
-    for dir in ${dirList[@]}; do
-        folderList=($(find ${ROOT}/${dir} -name '*cover*' -printf '%h\n' | awk '!seen[$0]++' | sed "s|${ROOT}/||g"))
-        for folder in ${folderList[@]}; do
-            import_tracks ${ROOT} "${folder}"
+    local GIT_DIR="${1}"; shift
+    local srcList=(${@})
+
+    for src in ${srcList}; do
+        if iszip ${src}; then
+            _msg EXEC "Uncompressing ${archive}"
+            7z x "${src}" -o"${_OPT_TMP}/${src}/" >${STDERR} 2>&1
+            local EXIT=$?
+            [[ ${EXIT} -eq 0 ]] && { _msg OK; local src="${_OPT_TMP}/${src}"; } || _msg WARN
+        fi    
+        local fileList=($(find "${src}" -name '*.flac' -o -name '*.mp3'))
+
+        for file in ${fileList}; do
+            if ismp3 ${file}; then
+                _msg EXEC "Converting ${file} to FLAC format"
+                med_convert flac ${file}
+                local EXIT=$?
+                [[ ${EXIT} -eq 0 ]] && _msg OK || { _msg WARN "Conversion of ${file} failed, continuing"; continue; }
+            fi
+            _msg EXEC "Consolidating ${file}"
+            import_track "${GIT_DIR}" "${file}"
+            local EXIT=$?
+            [[ ${EXIT} -eq 0 ]] && _msg OK || { _msg WARN "Consolidation of ${file} failed, continuing"; continue; }
         done
     done
+
+    local importList=($(find ${GIT_DIR}/.import/ -maxdepth 1 -type d -print '%p\t'))
+    for import in ${importList[@]}; do
+        _msg EXEC "Importing ${import}"
+        import_dir "${GIT_DIR}" "${import}"
+        local EXIT=$?
+        [[ ${EXIT} -eq 0 ]] && _msg OK || { _msg WARN "Importation of ${import} failed, continuing"; continue; }
+    done
+
 }
