[cmd_deploy] Fixed typo in git annex get graceful exit

diff --git a/src/cmd_deploy b/src/cmd_deploy
--- a/src/cmd_deploy
+++ b/src/cmd_deploy
@@ -56,7 +56,7 @@ cmd_deploy() {
         if _if_array_contains ${imageid} ${deployableidList[@]}; then
             local GIT_GET=false
             [[ ! -f "${GIT_DIR}/${imageid}.flac" ]] && { git -C  "${GIT_DIR}" annex get "${imageid}.flac" >${STDERR} 2>&1; local GIT_GET=true; }
-            [[ $? -ne 0 ]] && { _ansi up 2; echo -en '\033[K'; echo "[ ${COUNT} / ${#updateableidList[@]} ] ${Imageid} could not be downloaded from server"; cat ${STDERR}; local ERR=true; continue; }
+            [[ $? -ne 0 ]] && { _ansi up 2; echo -en '\033[K'; echo "[ ${COUNT} / ${#updateableidList[@]} ] ${imageid} could not be downloaded from server"; cat ${STDERR}; local ERR=true; continue; }
             deploy_cp "${GIT_DIR}" "${TARGET}" "${DB_FILE}" ${imageid} > ${STDERR} 2>&1
             [[ "${GIT_GET}" == "true" ]] && git -C "${GIT_DIR}" annex drop ${imageid}.flac >/dev/null 2>&1
             [[ $? -ne 0 ]] && { _ansi up 2; echo -en '\033[K'; echo "[ ${COUNT} / ${#updateableidList[@]} ] Copy of ${imageid} completed with errors"; cat ${STDERR}; local ERR=true; continue; } 
